/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.test.board.domain;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import java.io.Serializable;
import java.time.*;



// ----------- << imports@AAAAAAGCizqVefTMQRg= >>
// ----------- >>

@Entity
@Getter
@Setter
@NoArgsConstructor
@Table(name = "TEST01_POSTING")
// ----------- << class.annotations@AAAAAAGCizqVefTMQRg= >>
// ----------- >>
public class Posting implements Serializable {

    private static final long serialVersionUID = 4601078821216712071L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "POSTING_ID")
    // ----------- << attribute.annotations@AAAAAAGCizuR2/T2/TU= >>
    // ----------- >>
    private Long id;

    @Column(name = "TITLE")
    // ----------- << attribute.annotations@AAAAAAGCizwV4vT9yi4= >>
    // ----------- >>
    private String title;

    @Column(name = "CONTENT")
    // ----------- << attribute.annotations@AAAAAAGCizw81/UExnU= >>
    // ----------- >>
    private String content;

    @Column(name = "CREATED_DATE", updatable = false)
    // ----------- << attribute.annotations@AAAAAAGCiz4ehPUMg/0= >>
    // ----------- >>
    private LocalDateTime createdDate = LocalDateTime.now();


    @ManyToOne
    @JoinColumn(name = "OWNER_ID", referencedColumnName = "USER_ID")
    private User owner;
// ----------- << class.extras@AAAAAAGCizqVefTMQRg= >>
// ----------- >>
}