/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.test.board.domain;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGCi7a8IPUrOn4= >>
// ----------- >>

@Getter
@Setter
@NoArgsConstructor
// ----------- << class.annotations@AAAAAAGCi7a8IPUrOn4= >>
// ----------- >>
public class User {
    // ----------- << attribute.annotations@AAAAAAGCi8baZvVVSyo= >>
    // ----------- >>
    private Long id;

    // ----------- << attribute.annotations@AAAAAAGCi8clnPVcp5E= >>
    // ----------- >>
    private String loginId;

    // ----------- << attribute.annotations@AAAAAAGCi8++uvVjXh4= >>
    // ----------- >>
    private String password;

    // ----------- << attribute.annotations@AAAAAAGCi8/X1vVqlI4= >>
    // ----------- >>
    private String userName;

    // ----------- << attribute.annotations@AAAAAAGCi8/1L/VxBXE= >>
    // ----------- >>
    private String email;

    // ----------- << attribute.annotations@AAAAAAGCi9AL7fV4uwI= >>
    // ----------- >>
    private LocalDateTime createdDate;

// ----------- << class.extras@AAAAAAGCi7a8IPUrOn4= >>
// ----------- >>
}